### ISSUE TITLE
Consider handling DV_TEXT 'formatting' attribute 

### ISSUE THREAD

**Issue by freshehr** [better-care/web-template#4]
We found a discrepancy between the Ehrbase and Better structured formats

-see https://discourse.openehr.org/t/issue-with-structured-format/3528

Essentially the Better code if presented with a text value object  {comment : {|value: "some text"}} will flatten it to {comment: "some text"} but it only checks for contained 'mapping' attributes. Therefore fails if   {comment : {|value: "some text", |formatting:"plain"}} is in the underlylng data. 

Suggest that 'formatting' is detected and the full object is retained in that case.

**Comment by delopst** [comment]
Hi.

I need to discuss this with my colleagues since this corrections will change the actual format returned from Better EHR Server to the clients.

Since this is a braking change in the format returned back to the clients we could only do this in the next major version (if we will agree that the change is necessary).

I can leave this issue open and get back to you probbably at the start of the next week.

Regards, Primož

**Comment by delopst** [comment]
Hi.

I discussed this with my colleagues. 

We will add support for this in the master branch and our EHR Server will then use this in the next major release which is currently planned for June.

We can leave this issue open for now and I can notify you when this will be pushed to the master branch.

Regards, Primož

**Comment by mpolajnar** [comment]
This was finally fixed in 4.0.0, released today.
